# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tyler Priest's Blog
tagline:          'Adventuring'
description:      ''
url:              http://tylerpriest.com
baseurl:          '/'
paginate:         5

author:
  name:           'Tyler Priest'
  url:            https://twitter.com/messiahtyler

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/tylerpriest/tylerpriest.github.com

theme: jekyll-theme-cayman